name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Download Turbo Bob
      run: curl --fail --location --output bob https://function61.com/go/turbobob-latest-stable-linux-amd64 && chmod +x bob

    - name: Build with Turbo Bob
      run: ./bob build in-ci-autodetect-settings
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EVENTHORIZON: ${{ secrets.EVENTHORIZON }}
